require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/bundler'
require 'capistrano/rbenv'
require 'capistrano/postgresql'
require 'capistrano/rails'
require 'capistrano/unicorn_nginx'
