default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: paak_development
  username: paak
  password: 'paak2015'

test:
  <<: *default
  database: paak_test
  username: paak
  password: 'paak2015'

production:
  <<: *default
  database: paak_production
  username: paak
  password: 'paak2015'
